### ISSUE TITLE
probably rename `sum()`

### ISSUE THREAD

**Issue by beanumber** [danicamiguel/emetricsrsw#18]
This could conflicts, because `emetricsrsw::sum()` is now masking `base::sum()`, which users probably don't want. You could try something like `sum_stata()`, or even `sum_()`,...but....I wonder if just prefixing basically every function with `stata_` might the best solution. So instead you would have: `stata_sum()`, `stata_regress()`, etc. That way there is no change of a conflict, and you alert anyone reading the code to the fact that they are using the Stata wrappers.

**Comment by danicamiguel** [comment]
Thanks will make the changes!
